// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/movie.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MovieRequest struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Pagination           string   `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieRequest) Reset()         { *m = MovieRequest{} }
func (m *MovieRequest) String() string { return proto.CompactTextString(m) }
func (*MovieRequest) ProtoMessage()    {}
func (*MovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a86c5be385b8452, []int{0}
}

func (m *MovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieRequest.Unmarshal(m, b)
}
func (m *MovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieRequest.Marshal(b, m, deterministic)
}
func (m *MovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieRequest.Merge(m, src)
}
func (m *MovieRequest) XXX_Size() int {
	return xxx_messageInfo_MovieRequest.Size(m)
}
func (m *MovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MovieRequest proto.InternalMessageInfo

func (m *MovieRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *MovieRequest) GetPagination() string {
	if m != nil {
		return m.Pagination
	}
	return ""
}

type MovieDetail struct {
	Title                string   `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Year                 string   `protobuf:"bytes,2,opt,name=Year,proto3" json:"Year,omitempty"`
	ImdbID               string   `protobuf:"bytes,3,opt,name=ImdbID,proto3" json:"ImdbID,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Poster               string   `protobuf:"bytes,5,opt,name=Poster,proto3" json:"Poster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieDetail) Reset()         { *m = MovieDetail{} }
func (m *MovieDetail) String() string { return proto.CompactTextString(m) }
func (*MovieDetail) ProtoMessage()    {}
func (*MovieDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a86c5be385b8452, []int{1}
}

func (m *MovieDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieDetail.Unmarshal(m, b)
}
func (m *MovieDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieDetail.Marshal(b, m, deterministic)
}
func (m *MovieDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieDetail.Merge(m, src)
}
func (m *MovieDetail) XXX_Size() int {
	return xxx_messageInfo_MovieDetail.Size(m)
}
func (m *MovieDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieDetail.DiscardUnknown(m)
}

var xxx_messageInfo_MovieDetail proto.InternalMessageInfo

func (m *MovieDetail) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MovieDetail) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *MovieDetail) GetImdbID() string {
	if m != nil {
		return m.ImdbID
	}
	return ""
}

func (m *MovieDetail) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MovieDetail) GetPoster() string {
	if m != nil {
		return m.Poster
	}
	return ""
}

type MovieResponse struct {
	Search               []*MovieDetail `protobuf:"bytes,1,rep,name=Search,proto3" json:"Search,omitempty"`
	TotalResults         string         `protobuf:"bytes,2,opt,name=TotalResults,proto3" json:"TotalResults,omitempty"`
	Response             string         `protobuf:"bytes,3,opt,name=Response,proto3" json:"Response,omitempty"`
	Error                string         `protobuf:"bytes,4,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MovieResponse) Reset()         { *m = MovieResponse{} }
func (m *MovieResponse) String() string { return proto.CompactTextString(m) }
func (*MovieResponse) ProtoMessage()    {}
func (*MovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a86c5be385b8452, []int{2}
}

func (m *MovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieResponse.Unmarshal(m, b)
}
func (m *MovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieResponse.Marshal(b, m, deterministic)
}
func (m *MovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieResponse.Merge(m, src)
}
func (m *MovieResponse) XXX_Size() int {
	return xxx_messageInfo_MovieResponse.Size(m)
}
func (m *MovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MovieResponse proto.InternalMessageInfo

func (m *MovieResponse) GetSearch() []*MovieDetail {
	if m != nil {
		return m.Search
	}
	return nil
}

func (m *MovieResponse) GetTotalResults() string {
	if m != nil {
		return m.TotalResults
	}
	return ""
}

func (m *MovieResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func (m *MovieResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*MovieRequest)(nil), "movie.movieRequest")
	proto.RegisterType((*MovieDetail)(nil), "movie.MovieDetail")
	proto.RegisterType((*MovieResponse)(nil), "movie.movieResponse")
}

func init() { proto.RegisterFile("pb/movie.proto", fileDescriptor_1a86c5be385b8452) }

var fileDescriptor_1a86c5be385b8452 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x51, 0xc1, 0x6a, 0x2a, 0x31,
	0x14, 0x65, 0xd4, 0xf1, 0xbd, 0x77, 0xf5, 0xbd, 0xc5, 0x7d, 0x52, 0x06, 0x29, 0x22, 0xb3, 0x28,
	0xd2, 0x85, 0x03, 0xf6, 0x0f, 0x8a, 0x05, 0x5d, 0x14, 0xca, 0xe8, 0xa6, 0xee, 0x32, 0x7a, 0xb1,
	0xd3, 0xc6, 0x49, 0x9a, 0x44, 0x8b, 0x88, 0x9b, 0xfe, 0x41, 0xe9, 0xa7, 0xf5, 0x17, 0xfa, 0x21,
	0x65, 0x92, 0xd8, 0xea, 0x2e, 0xe7, 0xe4, 0xdc, 0xc3, 0xb9, 0xe7, 0xc2, 0x3f, 0x99, 0x25, 0x2b,
	0xb1, 0xc9, 0xa9, 0x2f, 0x95, 0x30, 0x02, 0x43, 0x0b, 0xda, 0xe7, 0x4b, 0x21, 0x96, 0x9c, 0x12,
	0x26, 0xf3, 0x84, 0x15, 0x85, 0x30, 0xcc, 0xe4, 0xa2, 0xd0, 0x4e, 0x14, 0x8f, 0xa0, 0x69, 0x65,
	0x29, 0x3d, 0xaf, 0x49, 0x1b, 0x8c, 0xe0, 0xd7, 0x13, 0x6d, 0x5f, 0x84, 0x5a, 0x44, 0x41, 0x37,
	0xe8, 0xfd, 0x49, 0x0f, 0x10, 0x3b, 0x00, 0x92, 0x2d, 0xf3, 0xc2, 0x8e, 0x47, 0x15, 0xfb, 0x79,
	0xc4, 0xc4, 0x3b, 0x68, 0xdc, 0x96, 0x4e, 0x43, 0x32, 0x2c, 0xe7, 0xd8, 0x82, 0x70, 0x9a, 0x1b,
	0x4e, 0xde, 0xc6, 0x01, 0x44, 0xa8, 0xdd, 0x13, 0x53, 0x7e, 0xdc, 0xbe, 0xf1, 0x0c, 0xea, 0xe3,
	0xd5, 0x22, 0x1b, 0x0f, 0xa3, 0xaa, 0x65, 0x3d, 0x2a, 0xb5, 0xd3, 0xad, 0xa4, 0xa8, 0xe6, 0xb4,
	0xe5, 0xbb, 0xd4, 0xde, 0x09, 0x6d, 0x48, 0x45, 0xa1, 0xd3, 0x3a, 0x14, 0xbf, 0x05, 0xf0, 0xd7,
	0xef, 0xa1, 0xa5, 0x28, 0x34, 0xe1, 0x25, 0xd4, 0x27, 0xc4, 0xd4, 0xfc, 0x21, 0x0a, 0xba, 0xd5,
	0x5e, 0x63, 0x80, 0x7d, 0xd7, 0xcd, 0x51, 0xc6, 0xd4, 0x2b, 0x30, 0x86, 0xe6, 0x54, 0x18, 0xc6,
	0x53, 0xd2, 0x6b, 0x6e, 0xb4, 0x4f, 0x77, 0xc2, 0x61, 0x1b, 0x7e, 0x1f, 0xbc, 0x7d, 0xce, 0x6f,
	0x5c, 0xee, 0x7a, 0xa3, 0x94, 0x50, 0x3e, 0xaa, 0x03, 0x83, 0x47, 0x5f, 0xed, 0x84, 0xd4, 0x26,
	0x9f, 0x13, 0xce, 0x20, 0x1c, 0x11, 0xe7, 0x02, 0xff, 0xfb, 0x28, 0xc7, 0xc5, 0xb7, 0x5b, 0xa7,
	0xa4, 0x73, 0x8e, 0x2f, 0x5e, 0x3f, 0x3e, 0xdf, 0x2b, 0x5d, 0xec, 0x24, 0xda, 0x46, 0x4d, 0x76,
	0xfe, 0x1c, 0xfb, 0x64, 0xf7, 0xd3, 0xfd, 0xfe, 0xba, 0x36, 0xab, 0xc8, 0x2c, 0xab, 0xdb, 0x9b,
	0x5e, 0x7d, 0x05, 0x00, 0x00, 0xff, 0xff, 0x25, 0x55, 0x4d, 0x83, 0x0a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MovieServiceClient is the client API for MovieService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MovieServiceClient interface {
	Hello(ctx context.Context, in *MovieRequest, opts ...grpc.CallOption) (*MovieResponse, error)
}

type movieServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMovieServiceClient(cc grpc.ClientConnInterface) MovieServiceClient {
	return &movieServiceClient{cc}
}

func (c *movieServiceClient) Hello(ctx context.Context, in *MovieRequest, opts ...grpc.CallOption) (*MovieResponse, error) {
	out := new(MovieResponse)
	err := c.cc.Invoke(ctx, "/movie.movieService/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieServiceServer is the server API for MovieService service.
type MovieServiceServer interface {
	Hello(context.Context, *MovieRequest) (*MovieResponse, error)
}

// UnimplementedMovieServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMovieServiceServer struct {
}

func (*UnimplementedMovieServiceServer) Hello(ctx context.Context, req *MovieRequest) (*MovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}

func RegisterMovieServiceServer(s *grpc.Server, srv MovieServiceServer) {
	s.RegisterService(&_MovieService_serviceDesc, srv)
}

func _MovieService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/movie.movieService/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).Hello(ctx, req.(*MovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MovieService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "movie.movieService",
	HandlerType: (*MovieServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _MovieService_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/movie.proto",
}
